### ISSUE TITLE
Change name for Context 

### ISSUE THREAD

**Issue by icerove** [near/near-sdk-as#137]
There are two name to import: context and Context. After I read the repo, I can know which one is which and use it differently. But their name is only one capital letter difference, which is really not friendly used. I see many file use `Context as VMContext`. Can we just change to VMContext or other better name?

**Comment by amgando** [comment]
For consistency this naming makes sense actually since it is the same thing but from different perspectives.  `context` is what you see inside an AS contract and `Context` is what you see inside unit tests.  aliasing the import is useful to make the difference explicit but you would never use both in the same code.

**Comment by amgando** [comment]
@icerove closing this as per our discussion last week.
